"""Declarative inventory for every job-watcher pipeline.

Keeping metadata in one place makes the pipeline/config/state relationship
testable without importing every fetcher and lets :mod:`run_company` replace
dozens of copy-pasted entry points.
"""
from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Literal


DescriptionFilter = Literal["none", "require_any_configured_term"]


@dataclass(frozen=True, slots=True)
class CompanyPipeline:
    slug: str
    source: str
    fetcher_module: str
    config_key: str
    seen_file: str
    description_filter: DescriptionFilter = "none"
    supports_keyword_filter: bool = True
    supports_location_filter: bool = False
    description_inline: bool = False
    newest_first: bool = False
    uses_playwright: bool = False

    @property
    def requires_tech_in_description(self) -> bool:
        return self.description_filter == "require_any_configured_term"


# slug, alert/display source, strict description filter.  The remaining names
# follow the conventions used by all 73 non-Microsoft adapters.
_PIPELINE_DATA = (
    ("abinbev", "AB InBev GCC", False),
    ("abb", "ABB", False),
    ("abbott", "Abbott Laboratories", False),
    ("accenture", "Accenture", True),
    ("adityabirla", "Aditya Birla Group", False),
    ("adobe", "Adobe", True),
    ("affine", "Affine Analytics", False),
    ("agoda", "Agoda", False),
    ("aig", "AIG", False),
    ("airbnb", "Airbnb", False),
    ("airbus", "Airbus", False),
    ("airindia", "Air India", False),
    ("airtel", "Bharti Airtel", False),
    ("akasaair", "Akasa Air", False),
    ("alegeus", "Alegeus", False),
    ("allianztech", "Allianz Technology", False),
    ("allstate", "Allstate", False),
    ("alphasense", "AlphaSense", False),
    ("alstom", "Alstom", False),
    ("amadeus", "Amadeus", False),
    ("amazon", "Amazon", False),
    ("amd", "AMD", False),
    ("amdocs", "Amdocs", False),
    ("americanairlines", "American Airlines", False),
    ("ameriprise", "Ameriprise", False),
    ("amex", "American Express", False),
    ("anz", "ANZ", False),
    ("aon", "Aon", False),
    ("apple", "Apple", False),
    ("apexgroup", "Apex Group", False),
    ("appliedsystems", "Applied Systems", False),
    ("aqr", "AQR", False),
    ("arcesium", "Arcesium", False),
    ("arista", "Arista Networks", False),
    ("arm", "Arm", False),
    ("aryng", "Aryng", False),
    ("ashokleyland", "Ashok Leyland", False),
    ("astrazeneca", "AstraZeneca", False),
    ("atlassian", "Atlassian", False),
    ("autodesk", "Autodesk", True),
    ("automationanywhere", "Automation Anywhere", False),
    ("axisbank", "Axis Bank", False),
    ("axtria", "Axtria", False),
    ("bajaj", "Bajaj Finance", False),
    ("bankofamerica", "Bank of America", True),
    ("barclays", "Barclays", False),
    ("bigbasket", "BigBasket", False),
    ("birlasoft", "Birlasoft", False),
    ("blackrock", "BlackRock", False),
    ("bloomberg", "Bloomberg", False),
    ("bmw", "BMW TechWorks India", False),
    ("bnpparibas", "BNP Paribas", False),
    ("bny", "BNY Mellon", False),
    ("boeing", "Boeing", False),
    ("bookingcom", "Booking.com", False),
    ("bosch", "Bosch", False),
    ("broadcom", "Broadcom", False),
    ("broadridge", "Broadridge", False),
    ("browserstack", "BrowserStack", False),
    ("canva", "Canva", False),
    ("cadence", "Cadence Design Systems", False),
    ("capgemini", "Capgemini", True),
    ("chubb", "Chubb", False),
    ("ciena", "Ciena", False),
    ("cisco", "Cisco", False),
    ("citi", "Citi", True),
    ("citiustech", "CitiusTech", True),
    ("clearwater", "Clearwater Analytics", False),
    ("clevertap", "CleverTap", False),
    ("cloudflare", "Cloudflare", False),
    ("comcast", "Comcast", False),
    ("coforge", "Coforge", False),
    ("cognizant", "Cognizant", True),
    ("continental", "Continental AG", False),
    ("cashfree", "Cashfree Payments", False),
    ("cred", "CRED", False),
    ("crisil", "CRISIL", False),
    ("crowdstrike", "CrowdStrike", False),
    ("citco", "Citco", False),
    ("cummins", "Cummins Inc.", False),
    ("cyient", "Cyient", False),
    ("daimlertruck", "Daimler Truck AG", False),
    ("darwinbox", "Darwinbox", False),
    ("databricks", "Databricks", False),
    ("datarobot", "DataRobot", False),
    ("dazn", "DAZN", False),
    ("definitivehealthcare", "Definitive Healthcare", False),
    ("dell", "Dell Technologies", False),
    ("deloitteusi", "Deloitte USI", False),
    ("delta", "Delta Air Lines", False),
    ("deltatre", "Deltatre", False),
    ("deltek", "Deltek", False),
    ("deshaw", "D. E. Shaw India", False),
    ("deutsche", "Deutsche Bank", False),
    ("disney", "Disney", False),
    ("doordash", "DoorDash", False),
    ("dover", "Dover", False),
    ("dtcc", "DTCC", False),
    ("dunbradstreet", "Dun & Bradstreet", False),
    ("duckcreek", "Duck Creek Technologies", False),
    ("dxc", "DXC Technology", True),
    ("ea", "Electronic Arts", False),
    ("ebay", "eBay", True),
    ("eclerx", "eClerx", True),
    ("eightfold", "Eightfold.ai", False),
    ("emerson", "Emerson", False),
    ("energyexemplar", "Energy Exemplar", False),
    ("epam", "EPAM Systems", False),
    ("ericsson", "Ericsson", False),
    ("eurofins", "Eurofins", False),
    ("equifax", "Equifax", False),
    ("evernorth", "Evernorth", False),
    ("expedia", "Expedia Group", False),
    ("eygds", "EY GDS", False),
    ("factset", "FactSet", False),
    ("ferguson", "Ferguson", False),
    ("fico", "FICO", False),
    ("fortinet", "Fortinet", False),
    ("fidelity", "Fidelity", False),
    ("fidelityinternational", "Fidelity International", False),
    ("finastra", "Finastra", False),
    ("firstamerican", "First American", True),
    ("fis", "FIS Global", False),
    ("fiserv", "Fiserv", False),
    ("flipkart", "Flipkart", False),
    ("fractal", "Fractal Analytics", False),
    ("franklintempleton", "Franklin Templeton", False),
    ("ford", "Ford Motor Company", False),
    ("freshworks", "Freshworks", False),
    ("gallagher", "Gallagher", False),
    ("geaerospace", "GE Aerospace", False),
    ("gehealthcare", "GE HealthCare", False),
    ("generalmotors", "General Motors", False),
    ("genpact", "Genpact", True),
    ("gevernova", "GE Vernova", False),
    ("gitlab", "GitLab", False),
    ("glean", "Glean", False),
    ("gsk", "GSK", False),
    ("globallogic", "GlobalLogic", False),
    ("globant", "Globant", False),
    ("godrej", "Godrej Industries Group", False),
    ("goldmansachs", "Goldman Sachs", False),
    ("google", "Google", False),
    ("grab", "Grab", False),
    ("gramener", "Gramener", False),
    ("groww", "Groww", False),
    ("guidewire", "Guidewire Software", False),
    ("happiestminds", "Happiest Minds", False),
    ("hartford", "The Hartford", False),
    ("hcltech", "HCLTech", True),
    ("hdfcbank", "HDFC Bank", False),
    ("healthedge", "HealthEdge", False),
    ("hexaware", "Hexaware", True),
    ("honeywell", "Honeywell", False),
    ("hsbc", "HSBC", False),
    ("ibm", "IBM", True),
    ("ice", "ICE", False),
    ("icertis", "Icertis", False),
    ("icicibank", "ICICI Bank", False),
    ("indegene", "Indegene", False),
    ("indigo", "IndiGo", False),
    ("infosys", "Infosys", True),
    ("ing", "ING", False),
    ("innovaccer", "Innovaccer", False),
    ("insightsoftware", "insightsoftware", False),
    ("intel", "Intel", False),
    ("intuit", "Intuit", False),
    ("invesco", "Invesco", False),
    ("irissoftware", "Iris Software", False),
    ("itc", "ITC Limited", False),
    ("ixigo", "ixigo", False),
    ("jioplatforms", "Jio Platforms", False),
    ("jnj", "Johnson & Johnson", False),
    ("jpmorgan", "JPMorgan Chase", False),
    ("jsw", "JSW Group", False),
    ("juspay", "Juspay", False),
    ("kotakbank", "Kotak Mahindra Bank", False),
    ("kpit", "KPIT Technologies", False),
    ("kpmgglobal", "KPMG Global Services", False),
    ("kyndryl", "Kyndryl", False),
    ("larsentoubro", "Larsen & Toubro", False),
    ("latentview", "LatentView Analytics", False),
    ("lenskart", "Lenskart", False),
    ("lloyds", "Lloyds Banking Group", True),
    ("lowes", "Lowe's", True),
    ("lseg", "LSEG", False),
    ("ltimindtree", "LTIMindtree", True),
    ("ltts", "LTTS", False),
    ("lufthansa", "Lufthansa Group", False),
    ("luxoft", "Luxoft", False),
    ("m2p", "M2P Fintech", False),
    ("macquarie", "Macquarie", False),
    ("maersk", "Maersk", False),
    ("mahindra", "Mahindra & Mahindra", False),
    ("makemytrip", "MakeMyTrip", False),
    ("marshmclennan", "Marsh McLennan", False),
    ("mastek", "Mastek", True),
    ("mastercard", "Mastercard", False),
    ("mbrdi", "Mercedes-Benz Research and Development India", False),
    ("mentorgraphics", "Siemens EDA (Mentor Graphics)", False),
    ("mks", "MKS Instruments", False),
    ("meesho", "Meesho", False),
    ("merck", "MSD (Merck & Co.)", False),
    ("meta", "Meta", False),
    ("metlife", "MetLife", False),
    ("medtronic", "Medtronic", False),
    ("micron", "Micron", True),
    ("moengage", "MoEngage", False),
    ("mongodb", "MongoDB", False),
    ("moodys", "Moody's", False),
    ("morganstanley", "Morgan Stanley", False),
    ("morningstar", "Morningstar", False),
    ("mphasis", "Mphasis", True),
    ("msci", "MSCI", False),
    ("mufg", "MUFG", False),
    ("murex", "Murex", False),
    ("nagarro", "Nagarro", False),
    ("nasdaq", "Nasdaq", False),
    ("natwest", "NatWest Group", False),
    ("navi", "Navi", False),
    ("necsws", "NEC Software Solutions", False),
    ("netflix", "Netflix", False),
    ("newgen", "Newgen Software", False),
    ("nielsen", "Nielsen", False),
    ("nokia", "Nokia", False),
    ("nomura", "Nomura", False),
    ("northerntrust", "Northern Trust", False),
    ("novartis", "Novartis", False),
    ("nutanix", "Nutanix", False),
    ("nucleussoftware", "Nucleus Software", False),
    ("nvidia", "Nvidia", False),
    ("nykaa", "Nykaa", False),
    ("omnissa", "Omnissa", False),
    ("observeai", "Observe.AI", False),
    ("okta", "Okta", False),
    ("ola", "Ola", False),
    ("optum", "Optum", False),
    ("oracle", "Oracle", True),
    ("payoneer", "Payoneer", False),
    ("paypal", "PayPal", False),
    ("paytm", "Paytm", False),
    ("pepsico", "PepsiCo India GCC", False),
    ("perfios", "Perfios", False),
    ("persistent", "Persistent Systems", True),
    ("pg", "Procter & Gamble", False),
    ("paloaltonetworks", "Palo Alto Networks", False),
    ("pfizer", "Pfizer", False),
    ("phonepe", "PhonePe", False),
    ("philips", "Philips", False),
    ("qatarairways", "Qatar Airways", False),
    ("policybazaar", "PolicyBazaar", False),
    ("postman", "Postman", False),
    ("priceline", "Priceline (Booking Holdings)", False),
    ("progresssoftware", "Progress Software", False),
    ("prudential", "Prudential", False),
    ("publicissapient", "Publicis Sapient", False),
    ("pwcac", "PwC Acceleration Centers", False),
    ("qualcomm", "Qualcomm", False),
    ("quantiphi", "Quantiphi", False),
    ("questsoftware", "Quest Software", False),
    ("razorpay", "Razorpay", False),
    ("reliance", "Reliance Industries", False),
    ("resideo", "Resideo", False),
    ("rippling", "Rippling", False),
    ("roche", "Roche", False),
    ("rockwell", "Rockwell Automation", False),
    ("sabre", "Sabre", True),
    ("salesforce", "Salesforce", False),
    ("sanofi", "Sanofi", False),
    ("saplabs", "SAP Labs", True),
    ("sapiens", "Sapiens International", False),
    ("sarvam", "Sarvam AI", False),
    ("safran", "Safran", False),
    ("saxobank", "Saxo Bank", False),
    ("schneiderelectric", "Schneider Electric", False),
    ("schwab", "Charles Schwab", True),
    ("servicenow", "ServiceNow", False),
    ("sharechat", "ShareChat", False),
    ("shell", "Shell", False),
    ("siemens", "Siemens", False),
    ("sigmoid", "Sigmoid Analytics", False),
    ("signzy", "Signzy", False),
    ("simcorp", "SimCorp", False),
    ("sita", "SITA", False),
    ("slice", "slice", False),
    ("smbc", "SMBC", False),
    ("snowflake", "Snowflake", False),
    ("societegenerale", "Societe Generale", True),
    ("sonatasoftware", "Sonata Software", False),
    ("soprasteria", "Sopra Steria", False),
    ("spglobal", "S&P Global", False),
    ("spglobal_careers", "S&P Global Careers", False),
    ("sprinklr", "Sprinklr", False),
    ("ssc", "SS&C Technologies", False),
    ("standardchartered", "Standard Chartered", False),
    ("statestreet", "State Street", True),
    ("stellantis", "Stellantis", False),
    ("stripe", "Stripe", False),
    ("swiggy", "Swiggy", False),
    ("swissre", "Swiss Re", True),
    ("synchrony", "Synchrony", False),
    ("synopsys", "Synopsys", False),
    ("sunlife", "Sun Life", False),
    ("target", "Target", False),
    ("tcs", "TCS", True),
    ("techmahindra", "Tech Mahindra", True),
    ("thomsonreuters", "Thomson Reuters", False),
    ("thoughtworks", "ThoughtWorks", False),
    ("ti", "Texas Instruments", False),
    ("tigeranalytics", "Tiger Analytics", False),
    ("towerresearch", "Tower Research Capital", False),
    ("transunioncibil", "TransUnion CIBIL", False),
    ("tredence", "Tredence", False),
    ("uber", "Uber", False),
    ("ubs", "UBS", False),
    ("ubisoft", "Ubisoft", False),
    ("uipath", "UiPath", False),
    ("unacademy", "Unacademy", False),
    ("uniphore", "Uniphore", False),
    ("unitedairlines", "United Airlines", False),
    ("upgrad", "upGrad", False),
    ("urbancompany", "Urban Company", False),
    ("vedanta", "Vedanta", False),
    ("verisk", "Verisk Analytics", False),
    ("verizon", "Verizon", False),
    ("virtusa", "Virtusa", True),
    ("visa", "Visa", False),
    ("volvocars", "Volvo Cars", False),
    ("volvogroup", "Volvo Group", False),
    ("walmart", "Walmart Global Tech", False),
    ("warnerbros", "Warner Bros. Discovery", False),
    ("wellsfargo", "Wells Fargo", True),
    ("whatfix", "Whatfix", False),
    ("wipro", "Wipro", True),
    ("wolterskluwer", "Wolters Kluwer", False),
    ("workday", "Workday", False),
    ("worldquant", "WorldQuant", False),
    ("wtw", "WTW", False),
    ("xoriant", "Xoriant", False),
    ("yash", "YASH Technologies", False),
    ("yubi", "Yubi", False),
    ("zensar", "Zensar Technologies", False),
    ("zerodha", "Zerodha", False),
    ("zeta", "Zeta", False),
    ("zscaler", "Zscaler", False),
    ("zoho", "Zoho Corporation", False),
    ("zf", "ZF Group", False),
    ("zomato", "Zomato", False),
    ("zynga", "Zynga", False),
    ("zsassociates", "ZS Associates", False),
    ("zurich", "Zurich Insurance", False),
    ("toyota", "Toyota Connected India", False),
    ("honda", "Honda Motorcycle & Scooter India (HMSI)", False),
    ("hyundai", "Hyundai Motor India Engineering (HMIE)", False),
    ("volkswagen", "Volkswagen Group Digital Solutions India", False),
    ("marutisuzuki", "Maruti Suzuki India", False),
    ("threem", "3M", False),
    ("caterpillar", "Caterpillar Inc.", False),
    ("whirlpool", "Whirlpool Corporation", False),
)

_IGNORES_KEYWORDS = frozenset(
    {
        "abinbev", "agoda", "airbnb", "airindia", "airtel", "akasaair", "allianztech", "allstate",
        "alphasense", "alstom", "axtria",
        "indegene", "latentview",
        "amd", "amdocs", "americanairlines", "anz", "arm",
        "appliedsystems", "aqr", "arcesium",
        "mentorgraphics", "synopsys",
        "atlassian",
        "bankofamerica", "bigbasket", "birlasoft", "bmw", "bnpparibas", "boeing", "bookingcom", "cashfree", "clearwater", "clevertap",
        "cloudflare", "coforge", "cognizant", "comcast", "continental",
        "cred", "crisil", "cummins", "cyient",
        "fortinet",
        "okta",
        "paloaltonetworks",
        "affine", "aryng", "ashokleyland",
        "daimlertruck", "darwinbox", "databricks", "datarobot", "dazn", "deloitteusi",
        "delta", "deltatre", "deshaw", "deutsche", "disney", "doordash", "dover", "dunbradstreet",
        "eightfold",
        "energyexemplar", "evernorth", "eygds", "ferguson", "flipkart", "ford", "gitlab", "glean", "globallogic", "globant",
        "godrej", "gramener", "gsk",
        "groww", "happiestminds", "hcltech",
        "honeywell", "ice", "indigo", "innovaccer",
        "infosys", "irissoftware", "itc", "jioplatforms", "jsw", "juspay",
        "kpit", "lenskart",
        "lufthansa", "m2p",
        "maersk", "makemytrip", "mastek", "mbrdi", "meesho", "mks", "moengage", "mongodb",
        "meta", "metlife", "morningstar", "msci", "natwest", "navi", "newgen", "nomura",
        "nucleussoftware", "observeai", "ola",
        "nykaa", "omnissa", "payoneer", "paytm", "perfios", "pg",
        "persistent", "policybazaar", "postman", "progresssoftware", "publicissapient",
        "qatarairways", "qualcomm", "questsoftware", "razorpay", "reliance", "resideo", "rippling",
        "safran", "salesforce", "sapiens", "sarvam", "saxobank",
        "schwab", "sigmoid",
        "servicenow", "snowflake", "stripe",
        "sharechat", "signzy", "simcorp", "sita",
        "slice",
        "societegenerale", "sonatasoftware", "standardchartered", "swiggy", "swissre",
        "techmahindra", "thoughtworks", "tigeranalytics", "towerresearch", "uber", "ubs", "uipath",
        "unacademy", "upgrad", "urbancompany", "vedanta",
        "whatfix", "wipro", "worldquant", "xoriant", "yash", "yubi", "zerodha", "zeta",
        "zoho", "zomato", "zscaler", "zsassociates", "zynga",
        "toyota", "honda", "hyundai", "volkswagen", "marutisuzuki",
        "whirlpool",
    }
)
_SUPPORTS_LOCATION = frozenset(
    {"amdocs", "aon", "apple", "gallagher", "google", "hsbc", "luxoft",
     "morganstanley", "netflix", "pepsico", "publicissapient", "qualcomm",
     "sapiens", "schneiderelectric", "servicenow", "siemens", "smbc", "spglobal_careers",
     "visa", "zurich"}
)
_INLINE_DESCRIPTIONS = frozenset(
    {
        "abinbev", "affine", "agoda", "airtel", "akasaair", "amazon", "amd", "aon", "arcesium",
        "atlassian", "bookingcom", "cashfree", "clevertap", "latentview",
        "cloudflare", "cognizant", "cred",
        "databricks", "dazn", "definitivehealthcare", "deshaw", "doordash", "dunbradstreet", "energyexemplar",
        "epam", "gallagher",
        "gitlab", "glean", "globant", "godrej", "google", "groww", "gsk", "healthedge", "ice",
        "indigo", "juspay",
        "kpit", "lenskart", "m2p", "mentorgraphics", "moengage", "mongodb",
        "meesho", "morningstar", "msci", "navi", "newgen", "nucleussoftware", "observeai", "okta", "payoneer", "paytm", "pepsico", "pg", "salesforce",
        "schneiderelectric",
        "sita",
        "sarvam", "sigmoid", "slice", "towerresearch", "uipath", "signzy", "snowflake", "stripe",
        "policybazaar", "postman", "publicissapient", "razorpay", "sharechat",
        "spglobal_careers", "urbancompany",
        "swiggy", "ubs", "unacademy", "whatfix", "worldquant", "xoriant", "yubi", "zerodha", "zeta", "zscaler",
        "zsassociates", "zynga",
        "hyundai", "marutisuzuki", "toyota",
    }
)
_NEWEST_FIRST = frozenset({"amazon", "amdocs", "natwest", "optum", "virtusa"})

# Fetchers that drive headless Firefox via Playwright's sync API. A
# ThreadPoolExecutor worker thread that runs one of these leaves an asyncio
# event loop permanently bound to it (Playwright's sync API never tears this
# down mid-process — these modules keep their browser alive as a
# process-lifetime singleton, closed only via atexit). If that same OS
# thread is later reused by the pool for a *different* Playwright-based
# company, the second one fails with "Playwright Sync API inside the
# asyncio loop" — confirmed live in production logs (every scheduled run
# since at least 2026-08-28 lost 7-8 of these companies to this collision).
# run_all.py uses this flag to give each one a dedicated thread instead of
# sharing the general pool, so no OS thread ever runs two of them.
_USES_PLAYWRIGHT = frozenset(
    {"ashokleyland", "axtria", "bigbasket", "bnpparibas", "darwinbox", "globallogic", "honeywell", "ibm", "indigo",
     "latentview", "natwest", "perfios", "safran", "servicenow", "sonatasoftware",
     "techmahindra", "uber", "unacademy", "upgrad", "virtusa",
     "toyota", "volkswagen"}
)


def _build_registry() -> dict[str, CompanyPipeline]:
    result = {
        "microsoft": CompanyPipeline(
            slug="microsoft",
            source="Microsoft",
            fetcher_module="fetcher",
            config_key="search",
            seen_file="seen_jobs.json",
            supports_location_filter=True,
            newest_first=True,
        )
    }
    for slug, source, strict in _PIPELINE_DATA:
        result[slug] = CompanyPipeline(
            slug=slug,
            source=source,
            fetcher_module=f"{slug}_fetcher",
            config_key=f"{slug}_search",
            seen_file=f"seen_jobs_{slug}.json",
            description_filter=(
                "require_any_configured_term" if strict else "none"
            ),
            supports_keyword_filter=slug not in _IGNORES_KEYWORDS,
            supports_location_filter=slug in _SUPPORTS_LOCATION,
            description_inline=slug in _INLINE_DESCRIPTIONS,
            newest_first=slug in _NEWEST_FIRST,
            uses_playwright=slug in _USES_PLAYWRIGHT,
        )
    return result


COMPANY_REGISTRY = MappingProxyType(_build_registry())


def get_company(slug: str) -> CompanyPipeline:
    """Return one pipeline definition with a useful error for CLI callers."""
    try:
        return COMPANY_REGISTRY[slug]
    except KeyError as exc:
        choices = ", ".join(COMPANY_REGISTRY)
        raise KeyError(f"unknown company slug {slug!r}; choose one of: {choices}") from exc
